language: java
jdk :
  - openjdk15
dist: bionic

addons:
  sonarcloud:
    organization: "AnastasiaDragalina"
    token: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AnastasiaDragalina_UIPR_Practice-6